spring:
  datasource:
    # 测试环境配置
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: redispsw
    jedis:
      pool:
        max-wait: 30000ms # 连接池最大阻塞时间
        max-active: 100 # 连接池最大连接数
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000ms # 连接超时