server:
  port: 9003
  servlet:
    context-path: /news

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://cloud:cloud@127.0.0.1:9001/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: service-news
  sql:
    init:
      enabled: false

  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      connection-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 30000
      idle-timeout: 30000
      connection-test-query: select 1

mybatis-plus:
  type-aliases-package: com.leiran.common.bean.*
  global-config:
    db-config:
      id-type: id_worker_str
      # 全局配置逻辑删除字段，应该使用bean的属性，而非sql列名
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: demo_tb_
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml