spring:
  datasource:
    # 生产环境配置
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=GMT%2B8
    username: demo_db
    password: demo_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: redispsw
    jedis:
      pool:
        max-wait: 30000ms
        max-active: 100
        max-idle: 20
        min-idle: 0
    timeout: 10000ms